### ISSUE TITLE
Add zhash value type

### ISSUE THREAD

**Issue by vrongmeal** [sdslabs/kiwi#13]
It would be great to have a "zhash" in standard set of values. This would be similar to zset (or scored set) with the difference that a zhash will have a value along with the score.

A zset can be thought of as:

| Key       | Score |
|-----------|-------|
| key_one   | 10    |
| key_two   | 20    |
| key_three | 30    |

whereas a zhash will be:

| Key       | Score | Value     |
|-----------|-------|-----------|
| key_one   | 10    | val_one   |
| key_two   | 20    | val_two   |
| key_three | 30    | val_three |

For documentation on how to add a new value type, see: https://kiwi.sdslabs.co/docs/add-new-value-type.html

**Comment by carmo-evan** [comment]
I'd like to take a stab at this, if that's ok.

**Comment by vrongmeal** [comment]
> I'd like to take a stab at this, if that's ok.

@carmo-evan Go ahead. That would be awesome!

**Comment by carmo-evan** [comment]
@vrongmeal Hi! Sorry, I just had a chance to look into it yesterday.

From what I can gather, zhash will be very similar to zset, and we can probably use the same underlying sortedSet value.

What would you like the API to be like? Do you want to be able to insert the value together with they key in the INSERT method, or do you want to do it in two steps - insert the key, and then update to set the value and the score?

Thank you!

**Comment by vrongmeal** [comment]
When inserting, you can do both the things. Parameters are dynamic. So if you get one parameter you can just insert it, if you get two, you can insert while setting the value. There will always be a "SET" action if someone wants to insert the key and then set the value.

**Comment by carmo-evan** [comment]
PR is up here https://github.com/sdslabs/kiwi/pull/17

**Comment by vrongmeal** [comment]
Closed through #17
