### ISSUE TITLE
Add benchmarking with other kv stores.

### ISSUE THREAD

**Issue by vrongmeal** [sdslabs/kiwi#14]
Compare performance and add benchmarking stats with other similar KV stores like [BuntDB](https://github.com/tidwall/buntdb).

This would help in better analyzing on how to improve performance when `Do`ing actions.

**Comment by agrim123** [comment]
Was just browsing through the code and came across [this](https://github.com/sdslabs/kiwi/blob/main/store.go#L16-L17)

Running benchmarks for `fmt.Errorf` vs `errors.New` when there are no directives being used.

<img width="471" alt="Screenshot 2020-09-08 at 2 30 11 PM" src="https://user-images.githubusercontent.com/16553016/92455850-cf87b580-f1df-11ea-9843-9ce7966e5cb2.png">

Also, for [this](https://github.com/sdslabs/kiwi/blob/main/store.go#L21-L23) as of now the input is only string, I think maybe we can change it to
```go
func newKeyErr(err error, key string) error {
	return e.Error() + ": " + key
}
```
Benchmarks for this:

<img width="515" alt="Screenshot 2020-09-08 at 2 36 54 PM" src="https://user-images.githubusercontent.com/16553016/92456593-c0553780-f1e0-11ea-8384-4e3af0fdfd0a.png">

Maybe we can find more of these bottleneck when we perform intensive bench marking!
