### ISSUE TITLE
Wrappers for other languages

### ISSUE THREAD

**Issue by VedantParanjape** [sdslabs/kiwi#15]
**Is your feature request related to a problem? Please describe.**
This doesn't have support for other languages.

**Describe the solution you'd like**
wrappers to languages like C++, python.

**Comment by vrongmeal** [comment]
Yes, it is not meant to be used for other languages. Kiwi, by structure, is not a dependency that can be accessed using a common API. It's just a Go library. The motivation was to produce a static binary for Go projects.

**Comment by VedantParanjape** [comment]
But, why can't it be extended to other languages ? I mean this is a great to use library, bindings can work with C++

**Comment by vrongmeal** [comment]
Yes the bindings can be used with a C++ projects but it wasn't really required by us.

Though if you'd be interested, I can reopen the issue if you want to work on them. I didn't really see an audience for using this in other languages.

**Comment by VedantParanjape** [comment]
I did want to work on this, but if there isn't any audience, never mind.

Regards,
Vedant Paranjape
