### ISSUE TITLE
[QUESTION] Any plans to make Kiwi a persistent store?

### ISSUE THREAD

**Issue by c0dzilla** [sdslabs/kiwi#19]

**Comment by vrongmeal** [comment]
I had plans of working on v2 which would also persist data. Current API isn't suitable for that and would require a lot of major changes. 

But, work on v2 won't be started soon since the current implementation fulfils what was required for our use.

**Comment by c0dzilla** [comment]
I see. I think this project can be a good base to understand and develop many interesting ideas. Durability is one aspect whose implementation would require interesting design choices i.e., whether to optimize for read-heavy or write-heavy workloads, how to store data on disk, how to index files(e.g. bloom filters), how and when to perform compactions, and many more. Could be a fruitful exercise!

**Comment by vrongmeal** [comment]
Yes. This is something I have been reading about and learning from other such projects like `RocksDB` or `BoltDB`. It's definitely something I would like to work on.
